# https://github.com/searxng/searxng/blob/master/searx/sxng_locales.py
locales = [
    "af",  # Afrikaans
    "ar",  # Arabic
    "ar-SA",  # Arabic
    "be",  # Belarusian
    "bg",  # Bulgarian
    "bg-BG",  # Bulgarian
    "ca",  # Catalan
    "cs",  # Czech
    "cs-CZ",  # Czech
    "cy",  # Welsh
    "da",  # Danish
    "da-DK",  # Danish
    "de",  # German
    "de-AT",  # German
    "de-BE",  # German
    "de-CH",  # German
    "de-DE",  # German
    "el",  # Greek
    "el-GR",  # Greek
    "en",  # English
    "en-AU",  # English
    "en-CA",  # English
    "en-GB",  # English
    "en-IE",  # English
    "en-IN",  # English
    "en-NZ",  # English
    "en-PH",  # English
    "en-PK",  # English
    "en-SG",  # English
    "en-US",  # English
    "en-ZA",  # English
    "es",  # Spanish
    "es-AR",  # Spanish
    "es-CL",  # Spanish
    "es-CO",  # Spanish
    "es-ES",  # Spanish
    "es-MX",  # Spanish
    "es-PE",  # Spanish
    "et",  # Estonian
    "et-EE",  # Estonian
    "eu",  # Basque
    "fa",  # Persian
    "fi",  # Finnish
    "fi-FI",  # Finnish
    "fr",  # French
    "fr-BE",  # French
    "fr-CA",  # French
    "fr-CH",  # French
    "fr-FR",  # French
    "ga",  # Irish
    "gd",  # Scottish Gaelic
    "gl",  # Galician
    "he",  # Hebrew
    "hi",  # Hindi
    "hr",  # Croatian
    "hu",  # Hungarian
    "hu-HU",  # Hungarian
    "id",  # Indonesian
    "id-ID",  # Indonesian
    "is",  # Icelandic
    "it",  # Italian
    "it-CH",  # Italian
    "it-IT",  # Italian
    "ja",  # Japanese
    "ja-JP",  # Japanese
    "kn",  # Kannada
    "ko",  # Korean
    "ko-KR",  # Korean
    "lt",  # Lithuanian
    "lv",  # Latvian
    "ml",  # Malayalam
    "mr",  # Marathi
    "nb",  # Norwegian Bokmål
    "nb-NO",  # Norwegian Bokmål
    "nl",  # Dutch
    "nl-BE",  # Dutch
    "nl-NL",  # Dutch
    "pl",  # Polish
    "pl-PL",  # Polish
    "pt",  # Portuguese
    "pt-BR",  # Portuguese
    "pt-PT",  # Portuguese
    "ro",  # Romanian
    "ro-RO",  # Romanian
    "ru",  # Russian
    "ru-RU",  # Russian
    "sk",  # Slovak
    "sl",  # Slovenian
    "sq",  # Albanian
    "sv",  # Swedish
    "sv-SE",  # Swedish
    "ta",  # Tamil
    "te",  # Telugu
    "th",  # Thai
    "th-TH",  # Thai
    "tr",  # Turkish
    "tr-TR",  # Turkish
    "uk",  # Ukrainian
    "ur",  # Urdu
    "vi",  # Vietnamese
    "vi-VN",  # Vietnamese
    "zh",  # Chinese
    "zh-CN",  # Chinese
    "zh-HK",  # Chinese
    "zh-TW",  # Chinese
    "all"  # All languages
]
